// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package doctortypepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DoctorTypeServiceClient is the client API for DoctorTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DoctorTypeServiceClient interface {
	RegisterDoctorType(ctx context.Context, in *RegisterDoctorTypeRequest, opts ...grpc.CallOption) (*RegisterDoctorTypeResponse, error)
}

type doctorTypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDoctorTypeServiceClient(cc grpc.ClientConnInterface) DoctorTypeServiceClient {
	return &doctorTypeServiceClient{cc}
}

func (c *doctorTypeServiceClient) RegisterDoctorType(ctx context.Context, in *RegisterDoctorTypeRequest, opts ...grpc.CallOption) (*RegisterDoctorTypeResponse, error) {
	out := new(RegisterDoctorTypeResponse)
	err := c.cc.Invoke(ctx, "/doctortypepb.DoctorTypeService/RegisterDoctorType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoctorTypeServiceServer is the server API for DoctorTypeService service.
// All implementations must embed UnimplementedDoctorTypeServiceServer
// for forward compatibility
type DoctorTypeServiceServer interface {
	RegisterDoctorType(context.Context, *RegisterDoctorTypeRequest) (*RegisterDoctorTypeResponse, error)
	mustEmbedUnimplementedDoctorTypeServiceServer()
}

// UnimplementedDoctorTypeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDoctorTypeServiceServer struct {
}

func (UnimplementedDoctorTypeServiceServer) RegisterDoctorType(context.Context, *RegisterDoctorTypeRequest) (*RegisterDoctorTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDoctorType not implemented")
}
func (UnimplementedDoctorTypeServiceServer) mustEmbedUnimplementedDoctorTypeServiceServer() {}

// UnsafeDoctorTypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DoctorTypeServiceServer will
// result in compilation errors.
type UnsafeDoctorTypeServiceServer interface {
	mustEmbedUnimplementedDoctorTypeServiceServer()
}

func RegisterDoctorTypeServiceServer(s grpc.ServiceRegistrar, srv DoctorTypeServiceServer) {
	s.RegisterService(&DoctorTypeService_ServiceDesc, srv)
}

func _DoctorTypeService_RegisterDoctorType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDoctorTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorTypeServiceServer).RegisterDoctorType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/doctortypepb.DoctorTypeService/RegisterDoctorType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorTypeServiceServer).RegisterDoctorType(ctx, req.(*RegisterDoctorTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DoctorTypeService_ServiceDesc is the grpc.ServiceDesc for DoctorTypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DoctorTypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "doctortypepb.DoctorTypeService",
	HandlerType: (*DoctorTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDoctorType",
			Handler:    _DoctorTypeService_RegisterDoctorType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main.go/gunk/v1/doctortype/all.proto",
}
